# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: YJL Jekyll Theme
description: >- # this means to ignore newlines until "baseurl:"
  YJL is a minimal Jekyll Theme.
baseurl: "/yuanjiale.github.io" # the subpath of the site
url: "https://yuanjialegithub.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: yuanjiale913@163.com
      link: mailto:yuanjiale913@163.com
    - name: WeChat
      value: 1933680295
      link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/yjlyjl5
      username: "@yjlyjl5"
  
    - name: GitHub
      link: http://github.com/yuanjialegithub
  

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
